ifndef LIB
	LIB := ../../lib
endif
export LIB

SOURCES = parser.mly lexer.mll load_logic.ml

INCLUDES = utils prover_syntax symbexe_syntax
RESULT = "$(LIB)/parsing"
OCAMLLDFLAGS="-a"

include ../Makefile.corestar